Repository Team-Recordy/Recordy-iOS, pull requests merged in 2024-11, with the labels that each got.

#164 [Feat] OverView, PlaceDetail뷰 구현
  App/Config/Secrets.xcconfig
  Common/Resources/Asset.xcassets/chevronLeft.imageset/Contents.json
  Common/Resources/Asset.xcassets/chevronLeft.imageset/chevronLeft.png
  Common/Resources/Asset.xcassets/chevronRight.imageset/Contents.json
  Common/Resources/Asset.xcassets/chevronRight.imageset/chevronRight.png
  Common/Resources/Asset.xcassets/location.imageset/location.png
  Common/Resources/Asset.xcassets/locationActive.imageset/Contents.json
  Common/Resources/Asset.xcassets/locationActive.imageset/location.png
  Common/Resources/Asset.xcassets/locationInactive.imageset/Contents.json
  Common/Resources/Asset.xcassets/locationInactive.imageset/locationInactive.png
  Common/Resources/Asset.xcassets/viskitLogo.imageset/Contents.json
  Common/Resources/Asset.xcassets/viskitLogo.imageset/viskitLogo.png
  Common/Sources/Components/ChipKeyWordButton.swift
  Common/Sources/Components/ExhibitionCollectionViewCell.swift
  Common/Sources/Components/PlaceDetailButton.swift
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Core/Sources/Model/OverView.swift
  Core/Sources/Model/Place.swift
  Core/Sources/Model/PlaceInfo.swift
  Core/Sources/Model/PlaceReview.swift
  Presentation/Sources/Home/View/ExhibitionListView.swift
  Presentation/Sources/Home/View/HomeViewController.swift
  Presentation/Sources/Home/View/MockData.swift
  Presentation/Sources/Home/View/OverviewViewController.swift
  Presentation/Sources/Home/View/PlaceDetailSegmentedControl.swift
  Presentation/Sources/Home/View/PlaceDetailViewController.swift
  Presentation/Sources/Home/View/ReviewFeedView.swift
  Presentation/Sources/Home/ViewModel/OverviewViewModel.swift
  Presentation/Sources/Home/ViewModel/PlaceDetailViewModel.swift
  Presentation/Sources/TabBar/RecordyTabBarController.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: 🎥 Feature, 형근

#162 [Refactor] MyPageView 수정사항 반영
  Common/Resources/Asset.xcassets/LedyEmpty.imageset/Contents.json
  Common/Resources/Asset.xcassets/LedyEmpty.imageset/LedyEmpty.svg
  Common/Sources/Components/ViskitYellowButton.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/BookMarkEmptyView.swift
  Presentation/Sources/MyProfile/View/BookMarkView.swift
  Presentation/Sources/MyProfile/View/MyPlaceEmptyView.swift
  Presentation/Sources/MyProfile/View/MyRecordEmptyView.swift
  Presentation/Sources/MyProfile/View/MyRecordView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
Labels: 🎥 Feature, ⚒️ Fix, 여경

#165 [Feat] TableView 수정
  Common/Resources/Asset.xcassets/alertImage.imageset/Contents.json
  Common/Resources/Asset.xcassets/alertImage.imageset/alertImage.svg
  Common/Resources/Asset.xcassets/apple.imageset/Contents.json
  Common/Resources/Asset.xcassets/apple.imageset/apple.svg
  Common/Resources/Asset.xcassets/kakao.imageset/Contents.json
  Common/Resources/Asset.xcassets/kakao.imageset/kakao.svg
  Common/Sources/Components/RecordyPopUpType.swift
  Common/Sources/Components/RecordyPopUpView.swift
  Presentation/Sources/MyProfile/Controller/ProfileEditViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/SettingViewController.swift
  Presentation/Sources/MyProfile/View/CustomTableView.swift
Labels: 🎥 Feature, ✏️ Refactoring, 여경
