Repository Team-Recordy/Recordy-iOS, pull requests merged in 2024-09, with the labels that each got.

#142 [Refactoring] Follow 리팩토링
  Common/Sources/Components/MediumButton.swift
  Core/Sources/Model/FollowerModel.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowerListRequest.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetFollowListResponse.swift
  Presentation/Sources/MyProfile/Controller/FollowViewController.swift
  Presentation/Sources/MyProfile/Controller/MyRecordViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/FollowerCell.swift
  Presentation/Sources/MyProfile/ViewModel/FollowViewModel.swift
  Presentation/Sources/MyProfile/ViewModel/FollowingViewModel.swift
Labels: ✏️ Refactoring, 여경

#145 [Chore] 순환 종속성 해결 후 빌드 되지 않는 문제 해결하기
  App/Project.swift
  App/Sources/SceneDelegate.swift
  Common/Project.swift
  Core/Project.swift
  Core/Sources/AWS/AWSS3Uploader.swift
  Core/Sources/Model/Keyword.swift
  Core/Sources/Notification/NotificationName+.swift
  Presentation/Project.swift
Labels: ✈️ ASAP, 🐜 Bug, ⚙️ Chore, 지석

#148 [Refactor] 데이터 모델링 진행
  Core/Sources/Model/FeedModel.swift
  Core/Sources/Model/Follow.swift
  Core/Sources/Model/Follower.swift
  Core/Sources/Model/Keyword.swift
  Core/Sources/Model/LocalVideo.swift
  Core/Sources/Model/MainRecord.swift
  Core/Sources/Model/OverView.swift
  Core/Sources/Model/Place.swift
  Core/Sources/Model/PlaceInfo.swift
  Core/Sources/Model/PlaceReview.swift
  Core/Sources/Model/ProfileUserModel.swift
  Core/Sources/Model/TasteData.swift
  Core/Sources/Model/UserRecord.swift
Labels: ✈️ ASAP, ✏️ Refactoring
