Repository Team-Recordy/Recordy-iOS, pull requests merged in 2024-07, with the labels that each got.

#2 [Chore] 기능 구현 전 Tuist 최종 세팅 마무리
  App/Project.swift
  Common/Project.swift
  Data/Project.swift
  Presentation/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+Project.swift
Labels: ⚙️ Chore

#6 [Feat] 애플 로그인 기능 구현
  App/App.entitlements
  App/Project.swift
  Core/Project.swift
  Core/Sources/Auth/AppleLoginManager.swift
  Presentation/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#11 [Feat] 영상 선택 UI 구현
  App/Project.swift
  App/Sources/AppDelegate.swift
  App/Sources/SceneDelegate.swift
  Common/Resources/Asset.xcassets/Color 1.colorset/Contents.json
  Common/Resources/Asset.xcassets/Color.colorset/Contents.json
  Common/Resources/Asset.xcassets/recordyBlack.colorset/Contents.json
  Common/Sources/Base/BaseNavigationController.swift
  Common/Sources/Extension/UICollectionViewCell+.swift
  Common/Sources/Extension/UIView+.swift
  Common/Sources/Extension/adaptive+.swift
  Core/Project.swift
  Core/Sources/Photos/PhotoKitManager.swift
  Presentation/Project.swift
  Presentation/Sources/UploadVideo/Cell/VideoCell.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🎥 Feature, 지석

#17 [Feat] RecordyTextField 구현
  Common/Sources/Extension/UITextField+.swift
  Common/Sources/Extension/UIView+.swift
  Common/Sources/RecordyTextField.swift
  Common/Sources/RecordyTextFieldStyle.swift
Labels: 🎥 Feature, 형근

#19 [FEAT] ButtonComponent 구현 #13
  App/Config/Secrets.xcconfig
  Common/Resources/Asset.xcassets/activate_check.imageset/Contents.json
  Common/Resources/Asset.xcassets/activate_check.imageset/activate_check.svg
  Common/Resources/Asset.xcassets/deactivate_check.imageset/Contents.json
  Common/Resources/Asset.xcassets/deactivate_check.imageset/deactivate_check.svg
  Common/Sources/AgreeButton.swift
  Common/Sources/RecordyButton.swift
Labels: 🎥 Feature, 여경

#28 [Feat] RecordyProgressView 구현
  Common/Sources/RecordyProgressView.swift
Labels: 🎥 Feature, 형근

#30 [FEAT] ProfileSegmentControllView 구현
  Common/Sources/Divider.swift
  Common/Sources/Font/RecordyFont.swift
  Common/Sources/RecordyToastMessageView.swift
  Presentation/Sources/MyProfile/View/ComponentType.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
Labels: 🎥 Feature, 여경

#15 [Feat] UploadVideoVC
  Core/Sources/Photos/PhotoKitManager.swift
  Presentation/Sources/UploadVideo/Cell/VideoCell.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/SelectVideoViewModel.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
Labels: 🎥 Feature, 지석

#32 [Feat] VideoVC UI
  Common/Resources/Asset.xcassets/bookmarkSelected.imageset/Contents.json
  Common/Resources/Asset.xcassets/bookmarkSelected.imageset/bookmark.png
  Common/Resources/Asset.xcassets/bookmarkUnselected.imageset/Contents.json
  Common/Resources/Asset.xcassets/bookmarkUnselected.imageset/bookmarkUnselected.png
  Common/Resources/Asset.xcassets/location.imageset/Contents.json
  Common/Resources/Asset.xcassets/location.imageset/location.png
  Common/Sources/Extension/String+.swift
  Common/Sources/Extension/UITextView+.swift
  Common/Sources/RecordyToggle.swift
  Core/Sources/Cache/VideoCacheManager.swift
  Core/Sources/Model/Feed.swift
  Presentation/Sources/Video/Cell/FeedCell.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: 🎥 Feature, 지석

#33 [Feat] 키체인 세팅
  Core/Sources/Keychain/KeychainManager.swift
  Core/Sources/Keychain/TokenType.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
Labels: 🎥 Feature, 지석

#37 [Feat] RecordyTextView 컴포넌트 구현
  Common/Sources/Components/AgreeButton.swift
  Common/Sources/Components/ChipKeyWordButton.swift
  Common/Sources/Components/Divider.swift
  Common/Sources/Components/FollowButton.swift
  Common/Sources/Components/MediumButton.swift
  Common/Sources/Components/RecordyButton.swift
  Common/Sources/Components/RecordyProgressView.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextFieldStyle.swift
  Common/Sources/Components/RecordyTextView.swift
  Common/Sources/Components/RecordyToastMessageView.swift
  Common/Sources/Components/RecordyToggle.swift
  Common/Sources/Components/SmallChipButton.swift
  Common/Sources/Components/TestViewController.swift
  Common/Sources/Extension/UIViewController+.swift
Labels: 🎥 Feature, 지석

#39 [Feat] LoginViewController 구현
  Common/Resources/Asset.xcassets/appleLogo.imageset/Contents.json
  Common/Resources/Asset.xcassets/appleLogo.imageset/appleLogo.svg
  Common/Resources/Asset.xcassets/kakaoLogo.imageset/Contents.json
  Common/Resources/Asset.xcassets/kakaoLogo.imageset/kakaoLogo.svg
  Common/Sources/LoginView.swift
  Common/Sources/LoginViewController.swift
Labels: 🎥 Feature, 형근

#40 [FEAT] profileInfoView
  Common/Resources/Asset.xcassets/profileImage.imageset/Contents.json
  Common/Resources/Asset.xcassets/profileImage.imageset/profileImage.svg
  Common/Sources/Components/Divider.swift
  Presentation/Sources/Model/ProfileUserModel.swift
  Presentation/Sources/MyProfile/View/ComponentType.swift
  Presentation/Sources/MyProfile/View/ProfileInfoView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
Labels: 🎥 Feature, 여경

#43 [Chore] TestViewController 삭제(#42)
  Common/Sources/Components/TestViewController.swift
Labels: ✈️ ASAP, ⚙️ Chore, 형근

#35 [Feat] API 세팅
  Core/Project.swift
  Core/Sources/Network/API/APITarget+Namespace.swift
  Core/Sources/Network/API/APITarget+Records.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/APIProvider.swift
  Core/Sources/Network/DTO/DTO+Namespace.swift
  Core/Sources/Network/DTO/Request/BaseResponse.swift
  Core/Sources/Network/DTO/Response/BaseRequest.swift
  Core/Sources/Network/NetworkError.swift
  Core/Sources/Network/RecordyPlugin.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: 🎥 Feature, 지석

#49 [chore] 불필요 파일 및 Data 모듈 제거
  App/Project.swift
  Core/Sources/Core.swift
  Data/Project.swift
  Data/Sources/Data.swift
  Presentation/Sources/Presentation.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+Project.swift
Labels: ✈️ ASAP, ⚙️ Chore, 지석

#45 [Feat] FilterComponents 구현
  Common/Project.swift
  Common/Resources/Asset.xcassets/closeButton.imageset/Contents.json
  Common/Resources/Asset.xcassets/closeButton.imageset/closeButton.png
  Common/Sources/Components/ChipKeyWordButton.swift
  Common/Sources/Components/LeftAlignedCollectionViewFlowLayout.swift
  Common/Sources/Components/RecordyFilteringCell.swift
  Common/Sources/Components/RecordyFilteringViewController.swift
  Core/Sources/Model/Keyword.swift
Labels: 🎥 Feature, 지석

#46 [FEAT] ProfileSettingViewController
  Common/Resources/Asset.xcassets/indicator.imageset/Contents.json
  Common/Resources/Asset.xcassets/indicator.imageset/indicator.svg
  Presentation/Sources/MyProfile/Controller/SetViewController.swift
  Presentation/Sources/MyProfile/View/CustomTableView.swift
Labels: 🎥 Feature, 여경

#50 [Feat] SignupView 구현
  Common/Resources/Asset.xcassets/signupComplete.imageset/Contents.json
  Common/Resources/Asset.xcassets/signupComplete.imageset/signupComplete.svg
  Common/Resources/Asset.xcassets/signupImage.imageset/Contents.json
  Common/Resources/Asset.xcassets/signupImage.imageset/signupBubble.svg
  Common/Sources/Components/AgreeButton.swift
  Common/Sources/Components/AgreeToAllButton.swift
  Common/Sources/Components/AgreeToggleButton.swift
  Common/Sources/Components/MoreButton.swift
  Common/Sources/Components/RecordyButton.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextFieldStyle.swift
  Common/Sources/Components/TermButton.swift
  Common/Sources/Extension/UILabel+.swift
  Common/Sources/Extension/UIStackView+.swift
  Core/Sources/Network/APIProvider.swift
  Core/Sources/Network/RecordyPlugin.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/View/CompleteView.swift
  Presentation/Sources/Signup/View/NicknameView.swift
  Presentation/Sources/Signup/View/TermsView.swift
Labels: 🎥 Feature, 형근

#52 [Chore] Login 관련 파일 모듈 이동
  Presentation/Sources/Login/LoginView.swift
  Presentation/Sources/Login/LoginViewController.swift
Labels: ✈️ ASAP, ⚙️ Chore, 형근

#54 [Feat] UploadVideoViewController 구현하기
  Common/Resources/Asset.xcassets/keywordButton.imageset/Contents.json
  Common/Resources/Asset.xcassets/keywordButton.imageset/keywordButton.png
  Common/Sources/Components/RecordyFilteringViewController.swift
  Common/Sources/Components/RecordyKeywordLabel.swift
  Common/Sources/Components/RecordySubtitleLabel.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextView.swift
  Common/Sources/Extension/UIViewController+.swift
  Core/Sources/Model/LocalVideo.swift
  Core/Sources/Network/DTO/Request/BaseResponse.swift
  Core/Sources/Network/DTO/Response/BaseRequest.swift
  Presentation/Sources/UploadVideo/Cell/VideoCell.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/SelectVideoViewModel.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#56 [Feat] 레코디 탭바 구현
  Common/Resources/Asset.xcassets/homeActive.imageset/Contents.json
  Common/Resources/Asset.xcassets/homeActive.imageset/homeActive.png
  Common/Resources/Asset.xcassets/homeInactive.imageset/Contents.json
  Common/Resources/Asset.xcassets/homeInactive.imageset/homeInactive.png
  Common/Resources/Asset.xcassets/profileActive.imageset/Contents.json
  Common/Resources/Asset.xcassets/profileActive.imageset/profileActive.png
  Common/Resources/Asset.xcassets/profileInactive.imageset/Contents.json
  Common/Resources/Asset.xcassets/profileInactive.imageset/profileInactive.png
  Common/Resources/Asset.xcassets/videoActive.imageset/Contents.json
  Common/Resources/Asset.xcassets/videoActive.imageset/videoActive.png
  Common/Resources/Asset.xcassets/videoInactive.imageset/Contents.json
  Common/Resources/Asset.xcassets/videoInactive.imageset/videoInactive.png
  Presentation/Sources/TabBar/RecordyTabBarController.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
Labels: 🎥 Feature, 지석

#61 [Feat] FollowerEmptyView 구현
  Common/Resources/Asset.xcassets/noFollowers.imageset/Contents.json
  Common/Resources/Asset.xcassets/noFollowers.imageset/noFollowers.svg
  Common/Resources/Asset.xcassets/text.imageset/Contents.json
  Common/Resources/Asset.xcassets/text.imageset/text.svg
  Common/Sources/Components/MediumButton.swift
  Core/Sources/Bindable/Bindable.swift
  Presentation/Sources/Model/FollowModel.swift
  Presentation/Sources/MyProfile/View/FollowerEmptyView.swift
  Presentation/Sources/MyProfile/View/FollowerViewController.swift
  Presentation/Sources/MyProfile/View/ProfileInfoView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
  Presentation/Sources/MyProfile/ViewModel/FollowersViewModel.swift
Labels: 🎥 Feature, 여경

#65 [Feat] FollowingView 구현
  Common/Resources/Asset.xcassets/yoo0profile.imageset/Contents.json
  Common/Resources/Asset.xcassets/yoo0profile.imageset/yoo0profile.svg
  Core/Sources/Bindable/Bindable.swift
  Presentation/Sources/Model/FollowerModel.swift
  Presentation/Sources/MyProfile/Controller/FollowingViewController.swift
  Presentation/Sources/MyProfile/ViewModel/FollowingViewModel.swift
Labels: 🎥 Feature, 여경

#62 [Feat] Signup 뷰 함수 구현
  Common/Resources/Asset.xcassets/activateCheck.imageset/Contents.json
  Common/Resources/Asset.xcassets/activateCheck.imageset/activate_check.svg
  Common/Resources/Asset.xcassets/deactivateCheck.imageset/Contents.json
  Common/Resources/Asset.xcassets/deactivateCheck.imageset/deactivate_check.svg
  Common/Sources/Components/RecordyButton.swift
  Common/Sources/Components/RecordyProgressView.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextFieldStyle.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/View/NicknameView.swift
Labels: 🎥 Feature, 형근

#59 [Feat] BaseNavigationController 세팅 끝내기
  Common/Sources/Base/BaseNavigationController.swift
  Common/Sources/Components/RecordyGradientView.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
Labels: 🎥 Feature, 지석

#69 [Feat] 마이페이지 내 취향 뷰 구현
  Common/Resources/Asset.xcassets/Gorecord.imageset/Contents.json
  Common/Resources/Asset.xcassets/Gorecord.imageset/Gorecord.svg
  Common/Resources/Asset.xcassets/bubbleBackImg.imageset/Contents.json
  Common/Resources/Asset.xcassets/bubbleBackImg.imageset/bubbleBackImg.svg
  Common/Resources/Asset.xcassets/bubbleChecked2 1.imageset/Contents.json
  Common/Resources/Asset.xcassets/bubbleChecked2 1.imageset/bubbleChecked2 1.svg
  Common/Resources/Asset.xcassets/mypageEmptyViewText.imageset/Contents.json
  Common/Resources/Asset.xcassets/mypageEmptyViewText.imageset/mypageEmptyViewText.svg
  Common/Resources/Asset.xcassets/mypagebubble.imageset/Contents.json
  Common/Resources/Asset.xcassets/mypagebubble.imageset/mypagebubble.svg
  Common/Resources/Font/Cocogoose Pro Thin-trial.ttf
  Common/Sources/Components/MypageRecordButton.swift
  Common/Sources/Font/RecordyFont.swift
  Presentation/Sources/Model/TasteData.swift
  Presentation/Sources/MyProfile/View/ProfileInfoView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteViewController.swift
  Presentation/Sources/MyProfile/ViewModel/TasteViewModel.swift
Labels: 🎥 Feature, 여경

#71 [Feat] 로그인 붙이기
  App/Project.swift
  Core/Sources/Auth/AppleLoginManager.swift
  Core/Sources/Model/SignIn.swift
  Core/Sources/Network/API/APITarget+Namespace.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/APIProvider.swift
  Core/Sources/Network/BaseURL.swift
  Core/Sources/Network/DTO/DTO+Namespace.swift
  Core/Sources/Network/DTO/Request/BaseRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+SignInRequest.swift
  Core/Sources/Network/DTO/Response/BaseResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+SignInResponse.swift
  Core/Sources/Network/NetworkError.swift
  Core/Sources/Network/RecordyNetworkError.swift
  Core/Sources/Network/RecordyPlugin.swift
  Core/Sources/OAuth/AppleLoginManager.swift
  Core/Sources/OAuth/KakaoLoginManager.swift
  Presentation/Sources/Login/LoginView.swift
  Presentation/Sources/Login/LoginViewController.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#67 [Feat] VideoFeedVC 디테일 건들기
  Common/Sources/Components/RecordyToggle.swift
  Presentation/Sources/Video/Cell/FeedCell.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: 🎥 Feature, 지석

#78 [Feat] 임시 화면 연결
  App/Sources/SceneDelegate.swift
  Common/Resources/Font/CocogooseProThin-trial.ttf
  Common/Sources/Components/RecordyFilteringViewController.swift
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Common/Sources/Extension/UICollectionViewCell+.swift
  Presentation/Sources/Home/HomeViewController.swift
  Presentation/Sources/MyProfile/View/TasteViewController.swift
  Presentation/Sources/TabBar/RecordyTabBarController.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#82 [Feat] Upload & SelectVideo 디테일 구현
  Common/Sources/Components/RecordyFilteringViewController.swift
  Common/Sources/Components/RecordyKeywordLabel.swift
  Common/Sources/Components/RecordySelectKeywordStackView.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextView.swift
  Common/Sources/Components/RecordyToastMessageView.swift
  Common/Sources/Extension/String+.swift
  Common/Sources/Extension/UIViewController+.swift
  Core/Sources/Model/Keyword.swift
  Presentation/Sources/UploadVideo/Cell/VideoCell.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#73 [Feat] 토큰 인터셉터 구현
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/BaseInterceptor.swift
  Core/Sources/Network/DTO/Request/Users/DTO+RefreshTokenRequest.swift
  Core/Sources/Network/DTO/Response/Users/DTO+RefreshTokenResponse.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#83 [Feat] MyPage EmptyView 연결
  Common/Resources/Asset.xcassets/BookmarkText.imageset/BookmarkText.svg
  Common/Resources/Asset.xcassets/BookmarkText.imageset/Contents.json
  Common/Resources/Asset.xcassets/Mypagebookmark.imageset/Contents.json
  Common/Resources/Asset.xcassets/Mypagebookmark.imageset/Mypagebookmark.svg
  Common/Resources/Asset.xcassets/myRecordText.imageset/Contents.json
  Common/Resources/Asset.xcassets/myRecordText.imageset/myRecordText.svg
  Common/Resources/Asset.xcassets/mypageCamera.imageset/Contents.json
  Common/Resources/Asset.xcassets/mypageCamera.imageset/mypageCamera.svg
  Core/Sources/Model/FeedModel.swift
  Presentation/Sources/MyProfile/Controller/FollowingViewController.swift
  Presentation/Sources/MyProfile/Controller/MyRecordViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/BookMarkView.swift
  Presentation/Sources/MyProfile/View/FollowerViewController.swift
  Presentation/Sources/MyProfile/View/MyRecordView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
  Presentation/Sources/MyProfile/View/RecordCollectionViewCell.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
  Presentation/Sources/MyProfile/ViewModel/MyRecordViewModel.swift
Labels: 🎥 Feature, 여경

#85 [Feat] API 연결 시작
  Core/Sources/Network/API/APITarget+Records.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/DTO/Request/Records/DTO+CreateRecordRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+DeleteRecordRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetBookmarkedListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetFamousRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetFollowingRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetRecentRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetUserRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+IsWatchedRecordRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+CheckNicknameRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+FollowRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowerListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetProfileRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+SignUpRequest.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetBookmarkedListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFamousRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFollowingRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetPresignedUrlResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecentRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetUserRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetFollowListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetFollowerListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetProfileResponse.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#93 [Feat] SytleCollectionView Sticky Header 구현
  Presentation/Sources/Home/HomeViewController.swift
Labels: 🎥 Feature, 형근

#89 Feature/#84
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Presentation/Sources/MyProfile/View/BookMarkView.swift
  Presentation/Sources/MyProfile/View/MyRecordView.swift
  Presentation/Sources/MyProfile/View/RecordCollectionViewCell.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
Labels: 🎥 Feature, 여경

#96 [Feat] Connect API to MyTasteView
  Core/Sources/Network/API/APITarget+Preference.swift
  Core/Sources/Network/DTO/Response/Preference/DTO+GetPreferenceResponse.swift
  Presentation/Sources/Model/TasteData.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
  Presentation/Sources/MyProfile/ViewModel/TasteViewModel.swift
Labels: 🎥 Feature, 여경

#98 [Feat] 마이페이지 뷰 API
  Core/Sources/Model/UserRecord.swift
  Core/Sources/Network/BaseInterceptor.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetUserRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+SignInResponse.swift
  Presentation/Sources/Login/LoginView.swift
  Presentation/Sources/Login/LoginViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/BookMarkView.swift
  Presentation/Sources/MyProfile/View/MyRecordView.swift
Labels: 🎥 Feature, 여경

#100 [Feat] Home 뷰 API 연동
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Core/Sources/Model/MainRecord.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFamousRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecentRecordListResponse.swift
  Presentation/Sources/Home/HomeViewController.swift
Labels: 🎥 Feature, 형근

#105 [Feat] PopUpView
  Common/Resources/Asset.xcassets/alert.imageset/Contents.json
  Common/Resources/Asset.xcassets/alert.imageset/alert.svg
  Common/Resources/Asset.xcassets/exit.imageset/Contents.json
  Common/Resources/Asset.xcassets/exit.imageset/exit.svg
  Common/Resources/Asset.xcassets/permission.imageset/Contents.json
  Common/Resources/Asset.xcassets/permission.imageset/permission.svg
  Common/Sources/Components/RecordyPopUpType.swift
  Common/Sources/Components/RecordyPopUpView.swift
Labels: 🎥 Feature, 여경

#107 [Feat] Splash Screen 구현
  App/Resources/Asset.xcassets/AppIcon.appiconset/Contents.json
  App/Resources/Asset.xcassets/Contents.json
  App/Resources/Asset.xcassets/splashAppLogo.imageset/Contents.json
  App/Resources/Asset.xcassets/splashAppLogo.imageset/appLogo.png
  App/Resources/Asset.xcassets/splashBackground.imageset/Contents.json
  App/Resources/Asset.xcassets/splashBackground.imageset/splashBackground.png
  App/Resources/LaunchScreen.storyboard
  Common/Resources/Asset.xcassets/loginAppLogo.imageset/Contents.json
  Common/Resources/Asset.xcassets/loginAppLogo.imageset/appLogo.png
  Presentation/Sources/Login/LoginView.swift
  Presentation/Sources/Login/SplashScreenViewController.swift
Labels: 🎥 Feature, 형근

#110 [Feat] Check The Detail in Main View Controller
  Common/Resources/Asset.xcassets/navigationImage.imageset/Contents.json
  Common/Resources/Asset.xcassets/navigationImage.imageset/navigationImage.png
  Common/Sources/Base/BaseNavigationController.swift
  Common/Sources/Components/ChipKeyWordButton.swift
  Common/Sources/Components/RecordyFilteringCell.swift
  Common/Sources/Components/RecordyPopUpView.swift
  Common/Sources/Components/RecordyPopUpViewController.swift
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Common/Sources/Extension/NotificationName+.swift
  Common/Sources/Extension/String+.swift
  Common/Sources/Extension/UIViewController+.swift
  Core/Sources/Network/API/APITarget+Records.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetFamousRecordListRequest.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetRecentRecordListRequest.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFamousRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecentRecordListResponse.swift
  Presentation/Sources/Home/HomeViewController.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
  Presentation/Sources/UploadVideo/SelectVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#112 [Feat] connect signup to main flow
  App/Sources/SceneDelegate.swift
  Common/Sources/Components/AgreeToAllButton.swift
  Common/Sources/Components/AgreeToggleButton.swift
  Common/Sources/Components/RecordyProgressView.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/TermButton.swift
  Core/Sources/Network/APIProvider.swift
  Core/Sources/Network/BaseInterceptor.swift
  Core/Sources/Network/DTO/Request/Users/DTO+SignUpRequest.swift
  Presentation/Sources/Login/LoginViewController.swift
  Presentation/Sources/Login/SplashScreenViewController.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/View/NicknameView.swift
  Presentation/Sources/Signup/View/TermsView.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#117 [Feat] video feed detail and other user profile connect(api, flows)
  App/Project.swift
  Common/Resources/Asset.xcassets/deleteButton.imageset/Contents.json
  Common/Resources/Asset.xcassets/deleteButton.imageset/delete.png
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Core/Sources/Model/Feed.swift
  Core/Sources/Model/User.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFamousRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecentRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetUserRecordListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetProfileResponse.swift
  Presentation/Sources/MyProfile/Controller/OtherUserProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/Video/Cell/FeedCell.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#120 [Fix] Textfield 수정
  Presentation/Sources/MyProfile/Controller/FollowerViewController.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/View/NicknameView.swift
Labels: ⚒️ Fix, 형근

#129 [Fix] 탭바 오류 수정
  Presentation/Sources/TabBar/RecordyTabBarController.swift
Labels: ✈️ ASAP, ⚒️ Fix, 형근

#130 [Feat] 팔로워 / 팔로잉 API 연결 및 마무리 작업
  Common/Sources/Components/AgreeToAllButton.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/TermButton.swift
  Common/Sources/Extension/UIViewController+.swift
  Core/Sources/AWS/AWSS3Uploader.swift
  Core/Sources/Model/User.swift
  Presentation/Sources/MyProfile/Controller/FollowViewController.swift
  Presentation/Sources/MyProfile/Controller/MyRecordViewController.swift
  Presentation/Sources/MyProfile/Controller/OtherUserProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/SetViewController.swift
  Presentation/Sources/MyProfile/View/CustomTableView.swift
  Presentation/Sources/MyProfile/View/FollowerEmptyView.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteEmptyView.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
  Presentation/Sources/MyProfile/ViewModel/FollowViewModel.swift
  Presentation/Sources/MyProfile/ViewModel/FollowingViewModel.swift
  Presentation/Sources/Signup/View/CompleteView.swift
  Presentation/Sources/Signup/View/TermsView.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
Labels: ✈️ ASAP, 🎥 Feature, 지석

#132 [Feat] Signup 뷰 약관 버튼 추가
  Common/Sources/Components/MoreButton.swift
  Presentation/Sources/Signup/View/TermsView.swift
Labels: 🎥 Feature, 형근
