Repository Team-Recordy/Recordy-iOS, pull requests merged in 2024-10, with the labels that each got.

#141 [Refactor] Signup 뷰 책임 분리
  Common/Sources/Components/AgreeAllTermButton.swift
  Common/Sources/Components/AgreeToAllButton.swift
  Common/Sources/Components/RecordyButton.swift
  Common/Sources/Components/RecordyProgressView.swift
  Common/Sources/Components/RecordyTermButton.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Components/RecordyTextFieldStyle.swift
  Common/Sources/Extension/String+.swift
  Common/Sources/Extension/UIViewController+.swift
  Presentation/Sources/Login/LoginViewController.swift
  Presentation/Sources/Signup/Controller/CompleteViewController.swift
  Presentation/Sources/Signup/Controller/NicknameViewController.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/Controller/TermsViewController.swift
  Presentation/Sources/Signup/View/CompleteView.swift
  Presentation/Sources/Signup/View/NicknameView.swift
  Presentation/Sources/Signup/View/SignupView.swift
  Presentation/Sources/Signup/View/TermsView.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
Labels: ✏️ Refactoring, 형근

#152 [Fix] 변수명 및 오류 수정
  Presentation/Sources/Signup/Controller/CompleteViewController.swift
  Presentation/Sources/Signup/Controller/NicknameViewController.swift
  Presentation/Sources/Signup/Controller/TermsViewController.swift
  Presentation/Sources/Signup/View/CompleteView.swift
  Presentation/Sources/Signup/View/TermsView.swift
Labels: ✈️ ASAP, ⚒️ Fix

#153 [Refactor] SignupView, HomeView 모델링 작업
  Presentation/Sources/Home/HomeViewController.swift
Labels: ✏️ Refactoring, 형근

#157 [Refactor] Viskit Font, Color 추가
  Common/Resources/Asset.xcassets/viskitAlert01.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitAlert02.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitBlack.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitBlack20.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitBlack30.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitBlack50.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitBlack70.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGradient.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray01.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray02.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray03.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray05.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray06.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray07.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray08.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray09.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray10.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitGray11.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitKakaoBrown.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitKakaoYellow.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitWhite.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow100.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow20.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow200.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow300.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow40.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow400.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow500.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow60.colorset/Contents.json
  Common/Resources/Asset.xcassets/viskitYellow80.colorset/Contents.json
  Common/Sources/Components/ViskitGradientView.swift
  Common/Sources/Font/ViskitFont.swift
Labels: ✈️ ASAP, ✏️ Refactoring, 형근

#158 [Refactor] ProfileView, FollowView 수정
  Core/Sources/Model/User.swift
  Presentation/Sources/MyProfile/Controller/FollowViewController.swift
  Presentation/Sources/MyProfile/Controller/OtherUserProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/PreviewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/MyPlaceEmptyView.swift
  Presentation/Sources/MyProfile/View/ProfileSegmentControllView.swift
  Presentation/Sources/MyProfile/View/TasteDataView.swift
  Presentation/Sources/MyProfile/View/TasteView.swift
  Presentation/Sources/MyProfile/ViewModel/FollowViewModel.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
Labels: ✏️ Refactoring, 여경
