Repository Team-Recordy/Recordy-iOS, pull requests merged in 2024-08, with the labels that each got.

#136 [Refactoring] VideoFeed 리펙토링, 캐싱 적용, 불필요 파일 제거
  Presentation/Sources/TabBar/RecordyTabBarType.swift
  Presentation/Sources/Video/UserProfileViewController.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
Labels: ⚒️ Fix, ✏️ Refactoring

#137 [Refactoring] SignupViewController 리팩토링
  Common/Sources/Components/RecordyProgressView.swift
  Common/Sources/Components/RecordyTextField.swift
  Common/Sources/Extension/String+.swift
  Presentation/Sources/Signup/Controller/SignupViewController.swift
  Presentation/Sources/Signup/View/NicknameView.swift
  Presentation/Sources/Signup/View/SignupView.swift
  Presentation/Sources/Signup/View/TermsView.swift
Labels: ✏️ Refactoring, 형근

#139 [Refactoring] UploadVideo 리펙토링
  Common/Project.swift
  Core/Project.swift
  Core/Sources/AWS/AWSS3Uploader.swift
  Core/Sources/Photos/PhotoKitManager.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewModel.swift
Labels: ✏️ Refactoring, 지석
