Repository Team-Recordy/Recordy-iOS, pull requests merged in 2025-02, with the labels that each got.

#198 [Feat] 프로필 수정 구현
  Common/Resources/Asset.xcassets/viskitImage/selctionCheck.imageset/Contents.json
  Common/Resources/Asset.xcassets/viskitImage/selctionCheck.imageset/btn_selection.png
  Common/Resources/Asset.xcassets/viskitImage/selctionCheck.imageset/btn_selection@2x.png
  Common/Resources/Asset.xcassets/viskitImage/selctionCheck.imageset/btn_selection@3x.png
  Common/Sources/Components/RecordyPopUpViewController.swift
  Presentation/Sources/MyProfile/Controller/CustomImagePickerViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileEditViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/SettingViewController.swift
  Presentation/Sources/MyProfile/View/ImageCell.swift
  Presentation/Sources/MyProfile/View/ProfileEditView.swift
  Presentation/Sources/MyProfile/View/ProfileInfoView.swift
  Presentation/Sources/Video/Cell/FeedCell.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: 🎥 Feature, 여경

#199 [Fix] 북마크 수정, 업로드 장소 등록 수정
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Presentation/Sources/Home/Cell/OverviewCollectionViewCell.swift
  Presentation/Sources/Home/View/OverviewViewController.swift
  Presentation/Sources/Home/View/PlaceDetailViewController.swift
  Presentation/Sources/Home/View/ReviewFeedView.swift
  Presentation/Sources/Home/ViewModel/OverviewViewModel.swift
  Presentation/Sources/Home/ViewModel/PlaceDetailViewModel.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/View/BookMarkView.swift
  Presentation/Sources/UploadVideo/RegisterPlace/RegisterPlaceSearchViewController.swift
  Presentation/Sources/UploadVideo/RegisterPlace/RegisterPlaceViewController.swift
  Presentation/Sources/UploadVideo/SearchPlace/SearchPlaceViewController.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: ⚒️ Fix, 형근

#203 [Feat] 타유저 프로필 구현
  Common/Resources/Asset.xcassets/viskitImage/locationCursor.imageset/Contents.json
  Common/Resources/Asset.xcassets/viskitImage/locationCursor.imageset/ic_cursor_16.png
  Common/Sources/Components/ThumbnailCollectionViewCell.swift
  Core/Sources/Model/User.swift
  Core/Sources/Network/DTO/Response/Records/DTO+GetFollowingRecordListResponse.swift
  Presentation/Sources/Home/View/OverviewViewController.swift
  Presentation/Sources/MyProfile/Controller/OtherUserProfileViewController.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
  Presentation/Sources/Video/View/FeedView.swift
Labels: 🎥 Feature, 형근

#204 [Feat] 마이페이지 API 연결
  Common/Sources/Extension/UIViewController+.swift
  Common/Sources/Extension/URL+.swift
  Core/Sources/Model/User.swift
  Core/Sources/Network/API/APITarget+Users.swift
  Core/Sources/Network/DTO/Request/Records/DTO+GetBookmarkedListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowerListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetFollowingListRequest.swift
  Core/Sources/Network/DTO/Request/Users/DTO+GetPresignedImageUrlRequest.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetFollowerListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetFollowingListResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetPresignedImageUrlResponse.swift
  Core/Sources/Network/DTO/Response/Users/DTO+GetProfileEditResponse.swift
  Presentation/Sources/Login/LoginViewController.swift
  Presentation/Sources/MyProfile/Controller/FollowViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileEditViewController.swift
  Presentation/Sources/MyProfile/Controller/ProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/SettingViewController.swift
  Presentation/Sources/MyProfile/View/FollowerCell.swift
  Presentation/Sources/MyProfile/View/FollowerEmptyView.swift
  Presentation/Sources/MyProfile/View/MyRecordView.swift
  Presentation/Sources/MyProfile/View/ProfileEditView.swift
  Presentation/Sources/MyProfile/ViewModel/FollowViewModel.swift
  Presentation/Sources/TabBar/RecordyTabBarType.swift
  Presentation/Sources/UploadVideo/UploadVideoViewController.swift
  Presentation/Sources/Video/VideoFeedViewModel.swift
Labels: 🎥 Feature, 여경

#206 [Fix] 2차 QA 수정
  App/Resources/Asset.xcassets/AppIcon.appiconset/appstore.png
  Common/Resources/Asset.xcassets/viskitImage/viskitLogo.imageset/viskitLogo.png
  Common/Sources/Extension/UIViewController+.swift
  Presentation/Sources/Home/ViewModel/OverviewViewModel.swift
  Presentation/Sources/MyProfile/Controller/OtherUserProfileViewController.swift
  Presentation/Sources/MyProfile/Controller/SettingViewController.swift
  Presentation/Sources/Search/SearchCompleteCollectionViewCell.swift
  Presentation/Sources/Search/SearchViewController.swift
  Presentation/Sources/UploadVideo/Cell/VideoCell.swift
  Presentation/Sources/UploadVideo/RegisterPlace/RegisterPlaceSearchViewController.swift
  Presentation/Sources/UploadVideo/RegisterPlace/RegisterPlaceViewController.swift
  Presentation/Sources/UploadVideo/SearchPlace/SearchPlaceViewController.swift
  Presentation/Sources/Video/VideoFeedViewController.swift
Labels: ⚒️ Fix, 형근
